### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by sbblin** [erfianugrah/revista-3#3]
Hi, Erfi 👋🏻

I find this Astro project from the Astro official website, and I really love this blog template you made!!!

I was wondering if this revista project is free to anyone who wants to use?
If yes, would you mind adding an open source license e.g. MIT, that would really nice, thanks~

**Comment by erfianugrah** [comment]
Hi @sbblin,

Yes it is free to use, that's a good call out, I'll add that

**Comment by erfianugrah** [comment]
Done!

**Comment by sbblin** [comment]
appreciate it!!
